# YAML file format
## SCRIPT PARAMETERS - ADAPT HERE

# Directory with input fastq files and reference genome
DATADIR: "/shared/home/courcellem/MORBILLIVIRUS/ASSEMBLY_SNAKE/data/"

# Reads file extension (FIRST PART OF FILENAME WILL BE USED AS SAMPLE ID)
ext1: ".1.fastq.gz"
ext2: ".2.fastq.gz"

# Reference genome file
refgen: "ref/Thailande_T7consensus.fasta"

# Cleaning parameters
# length = minimum read length to be kept
length: 125

# Mapping parameters
# threads = number of threads
threads: 2

# Consensus building parameters
# mincov = the minimum number of reads covering a site (otherwise: N)
mincov: 2
# minfrac = If the second most frequent type is at least H fraction of the most common type then a heterozygous base type will be reported in the consensus
minfrac: 0.9
# minQ = minimum read mapping quality score (read is skipped if lower)
minQ: 51

