# YAML file format
## SCRIPT PARAMETERS - ADAPT HERE

# Directory with input fastq files and reference genome
DATADIR: "/shared/home/courcellem/MORBILLIVIRUS/ASSEMBLY_SNAKE/data/"

# Reads file extension (FIRST PART OF FILENAME WILL BE USED AS SAMPLE ID)
ext1: "_R1_001.fastq.gz"
ext2: "_R2_001.fastq.gz"

# Reference genome file
refgen: "ref/EU267273.fasta"

# Variant calling parameters
# mincov = the minimum number of reads covering a site to be considered (snippy default=10)
mincov: 10
# min frac = the minimum proportion of those reads which must differ from the reference
minfrac: 0.50

# Consensus building parameters
# low coverage threshold
lowcov: 10
